HoTuanPhuoc/Models/SACH.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoTuanPhuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.VIETSACHes = new HashSet<VIETSACH>();
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> MaCD { get; set; }
        public Nullable<int> MaNXB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIETSACH> VIETSACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}

HoTuanPhuoc/Areas/admin/Controllers/SachController.cs
using HoTuanPhuoc.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace HoTuanPhuoc.Areas.admin.Controllers
{
    public class SachController : BaseAdminController
    {
        // GET: admin/Sach
        SachOnlineEntities db = new SachOnlineEntities();
        public ActionResult Index(int? page, string strSearch)
        {
            int iSize = 7;
            int iPageNumber = page ?? 1;
            ViewBag.Search = strSearch ?? "";
            if (string.IsNullOrEmpty(strSearch))
            {
                List<SACH> kq = db.SACHes.OrderBy(a => a.MaSach).ToList();
                return View(kq.ToPagedList(iPageNumber, iSize));

            }
            else
            {
                List<SACH> kq = db.SACHes.Where(c => c.TenSach.Contains(strSearch)
                    || c.MoTa.Contains(strSearch)
                    || c.CHUDE.TenChuDe.Contains(strSearch)
                    || c.NHAXUATBAN.TenNXB.Contains(strSearch)).OrderBy(a => a.MaSach).ToList();
                return View(kq.ToPagedList(iPageNumber, iSize));

            }
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.MaCD = new SelectList(db.CHUDEs.ToList().OrderBy(a => a.TenChuDe), "MaCD", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NHAXUATBANs.ToList().OrderBy(a => a.TenNXB), "MaNXB", "TenNXB");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection f, SACH sach, HttpPostedFileBase fFileUpload)
        {
            ViewBag.MaCD = new SelectList(db.CHUDEs.ToList().OrderBy(a => a.TenChuDe), "MaCD", "TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NHAXUATBANs.ToList().OrderBy(a => a.TenNXB), "MaNXB", "TenNXB");
            if (fFileUpload == null)
            {
                //Nội dung thông báo yêu cầu chọn ảnh bìa
                ViewBag.ThongBao = "Hãy chọn ảnh bìa.";
                //Lưu thông tin để khi load lại trang do yêu cầu chọn ảnh bìa sẽ hiển thị   các thông tin này lên trang
                ViewBag.TenSach = f["sTenSach"];
                ViewBag.MoTa = f["sMoTa"];
                ViewBag.SoLuong = int.Parse(f["iSoLuong"]);
                ViewBag.GiaBan = decimal.Parse(f["mGiaBan"]);
                ViewBag.MaCD = new SelectList(db.CHUDEs.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe", int.Parse(f["MaCD"]));
                ViewBag.MaNXB = new SelectList(db.NHAXUATBANs.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", int.Parse(f["MaNXB"]));
                return View();
            }
            else
            {

                if (ModelState.IsValid)
                {
                    //Lấy tên file (Khai báo thư viện: System.IO)
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    sFileName = RemoveDiacritics2(sFileName);

                    //Lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName); //Kiểm tra ảnh bìa đã tồn tại chưa để lưu lên thư mục
                    using (var img = System.Drawing.Image.FromStream(fFileUpload.InputStream))
                    {
                        var resizedImg = new Bitmap(img, new Size(400, 500));
                        resizedImg.Save(path, img.RawFormat);
                    }

                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);

                    }
                    //Lưu Sạch vào CSDL
                    sach.TenSach = f["sTenSach"];
                    sach.MoTa = f["sMoTa"];
                    sach.AnhBia = sFileName;
                    DateTime ngayCapNhat;
                    if (DateTime.TryParse(f["dNgayCapNhat"], out ngayCapNhat))
                    {
                        sach.NgayCapNhat = ngayCapNhat;
                    }
                    sach.SoLuongBan = int.Parse(f["iSoLuong"]);
                    sach.GiaBan = decimal.Parse(f["mGiaBan"]);
                    sach.MaCD = int.Parse(f["MaCD"]);
                    sach.MaNXB = int.Parse(f["MaNXB"]);
                    db.SACHes.Add(sach);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            SACH sach = db.SACHes.SingleOrDefault(n => n.MaSach == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        public ActionResult Delete(int id)
        {
            SACH sach = db.SACHes.SingleOrDefault(n => n.MaSach == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, FormCollection f)
        {
            var sach = db.SACHes.SingleOrDefault(n => n.MaSach == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            var ctdh = db.CHITIETDATHANGs.Where(ct => ct.MaSach == id);
            if (ctdh.Count() > 0)
            {
                ViewBag.ThongBao = "Sách này đang có trong bảng Chi tiết đặt hàng <br> Nếu muốn xóa thì phải xóa hết mã sách này trong bảng Chi tiết đặt hàng";
                return View(sach);
            }

            var vietsach = db.VIETSACHes.Where(vs => vs.MaSach == id).ToList();
            if (vietsach != null)
            {
                db.VIETSACHes.RemoveRange(vietsach);

                db.SaveChanges();
            }


            db.SACHes.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var sach = db.SACHes.SingleOrDefault(n => n.MaSach == id);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            ViewBag.MaCD = new SelectList(db.CHUDEs.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe", sach.MaCD);
            ViewBag.MaNXB = new SelectList(db.NHAXUATBANs.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);

            return View(sach);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            int masach = int.Parse(f["MaSach"]);
            var sach = db.SACHes.SingleOrDefault(n => n.MaSach == masach);
            ViewBag.MaCD = new SelectList(db.CHUDEs.ToList().OrderBy(n => n.TenChuDe), "MaCD", "TenChuDe", sach.MaCD);
            ViewBag.MaNXB = new SelectList(db.NHAXUATBANs.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);
            if (ModelState.IsValid)
            {
                if (fFileUpload != null)
                {
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    sFileName = RemoveDiacritics2(sFileName);

                    //Lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName); //Kiểm tra ảnh bìa đã tồn tại chưa để lưu lên thư mục
                    using (var img = System.Drawing.Image.FromStream(fFileUpload.InputStream))
                    {
                        var resizedImg = new Bitmap(img, new Size(400, 500));
                        resizedImg.Save(path, img.RawFormat);
                    }

                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    sach.AnhBia = sFileName;
                }

                sach.TenSach = f["TenSach"];
                sach.MoTa = f["MoTa"];
                sach.NgayCapNhat = Convert.ToDateTime(f["dNgayCapNhat"]);
                sach.SoLuongBan = int.Parse(f["iSoLuong"]);
                sach.GiaBan = decimal.Parse(f["mGiaBan"]);
                sach.MaCD = int.Parse(f["MaCD"]);
                sach.MaNXB = int.Parse(f["MaNXB"]);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sach);
        }
        private string RemoveDiacritics2(string text)
        {
            var normalizedString = text.Normalize(NormalizationForm.FormD);
            var stringBuilder = new StringBuilder();

            foreach (var c in normalizedString)
            {
                var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);
                if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                {
                    stringBuilder.Append(c);
                }
            }

            return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
        }


    }
}

HoTuanPhuoc/Areas/admin/Views/Sach/Create.cshtml
@model HoTuanPhuoc.Models.SACH

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Thêm sách</h2>


@using (Html.BeginForm("Create", "Sach", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SACH</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tên sách</label>
            <div class="col-md-10">
                <input type="text" size="70" name="sTenSach" value="@ViewBag.TenSach" required />
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mô tả</label>
            <div class="col-md-10">
                <textarea name="sMoTa" id="mota">@ViewBag.MoTa </textarea>
                <script src="~/ckeditor/ckeditor.js"></script>
                <script src="~/ckfinder/ckfinder.js"></script>

                <script>
                    CKEDITOR.replace("mota", {
                        extraAllowedContent: 'span',
                        customConfig: '/ckeditor/config.js',
                    
                    });
                </script>


                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ảnh bìa</label>
            <div class="col-md-10">
                <input type="file" name="fFileUpload" />
                @ViewBag.ThongBao
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày cập nhật</label>
            <div class="col-md-10">
                <input type="date" name="dNgayCapNhat" required />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Số lượng </label>
            <div class="col-md-10">
                <input type="number" min="1" required name="iSoLuong" value="@ViewBag.SoLuong" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Giá bán </label>
            <div class="col-md-10">
                <input type="number" min="1" required name="mGiaBan" value="@ViewBag.GiaBan" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chủ đề </label>
            <div class="col-md-10">
                @Html.DropDownList("MaCD", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaCD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nhà xuất bản </label>
            <div class="col-md-10">
                @Html.DropDownList("MaNXB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNXB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HoTuanPhuoc/Areas/admin/Views/Sach/Delete.cshtml
@model HoTuanPhuoc.Models.SACH

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

}
<style type="text/css">
    img {
        width: 200px;
        margin-bottom: 20px;
    }

    h3, h4 {
        color: red;
        font-weight: bold;
    }
</style>
<h2>XÁC NHẬN THÔNG TIN CẦN XÓA</h2>

<h3>Bạn quyết định xóa quyển sách này?</h3>
<h4>@Html.Raw(ViewBag.ThongBao)</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>Tên sách:</dt>
        <dd>@Html.DisplayFor(model => model.TenSach)</dd>
        <dt> Mô tả: </dt>
        <dd>
            @Html.Raw(@Model.MoTa.ToString().Replace("\n",
       "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </dd>
        <dt> Ảnh bìa: </dt>
        <dd> <img src="~/Images/@Model.AnhBia" alt=" @Model.TenSach"> </dd>
        <dt> Ngày cập nhật:</dt>
        <dd> @Html.FormatValue(@Model.NgayCapNhat, "{0:dd/MM/yyyy}") </dd>
        <dt> Số lượng bán: </dt>
        <dd> @Html.DisplayFor(model => model.SoLuongBan)</dd>
        <dt>Giá bán: </dt>
        <dd> @Html.FormatValue(@Model.GiaBan, "{0:#,##0}") VNĐ</dd>
        <dt>Chủ đề:</dt>
        <dd>@Html.DisplayFor(model => model.CHUDE.TenChuDe)</dd>
        <dt>Nhà xuất bản:</dt>
        <dd>@Html.DisplayFor(model => model.NHAXUATBAN.TenNXB)</dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="XÓA" class="btn btn-default" /> | @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
        </div>
    }
</div>

HoTuanPhuoc/Areas/admin/Views/Sach/Details.cshtml
@model HoTuanPhuoc.Models.SACH

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style type="text/css">
    .img {
        width: 200px;
        margin-bottom: 20px;
    }

    .dl-horizontal dt {
        width: 150px;
        float: left;
        clear: left;
        text-align: left;
        font-weight: bold;
    }

    .dl-horizontal dd {
        margin-left: 160px;
    }

    h2 {
        text-align: center;
    }
</style>

<h2>CHI TIẾT SÁCH</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên sách:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            Mô tả:
        </dt>
        <dd>
            @Html.Raw(@Model.MoTa.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </dd>
        <dt>
            Ảnh Bìa
        </dt>
        <dd>
            <img class="img" src="~/Images/@Model.AnhBia" alt="@Model.TenSach">
        </dd>
        <dt>
            Ngày cập nhật:
        </dt>
        <dd>
            @Html.FormatValue(@Model.NgayCapNhat, "{0:dd/MM/yyyy}")
        </dd>
        <dt>
            Số lượng bản:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SoLuongBan)
        </dd>
        <dt>
            Giá bán:
        </dt>
        <dd>
            @Html.FormatValue(@Model.GiaBan, "{0:#,##0}") VND
        </dd>
        <dt>
            Chủ đề:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CHUDE.TenChuDe)
        </dd>

        <dt>
            Nhà xuất bản:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NHAXUATBAN.TenNXB)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaSach }) | @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
</p>

HoTuanPhuoc/Areas/admin/Views/Sach/Edit.cshtml
@model HoTuanPhuoc.Models.SACH

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<script src="~/ckeditor/ckeditor.js"></script>
<h2>ĐIỀU CHỈNH THÔNG TIN SÁCH</h2>
@using (Html.BeginForm("Edit", "Sach", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-2">Mã sách:</label>
            <div class="col-md-10">
                @*Chỉ hiển thị mã sách không cho sửa*@
                <input type="text" size="70" name="MaSach" value="@Model.MaSach" readonly />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tên sách:</label>
            <div class="col-md-10">
                <input type="text" size="70" name="TenSach" value="@Model.TenSach" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Mô tả:</label>
            <div class="col-md-10">
                <textarea name="MoTa" id="mota">@Model.MoTa</textarea>
                <script>CKEDITOR.replace('mota');</script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ảnh bìa:</label>
            <div class="col-md-10">
                <input type="file" name="fFileUpload" />
                <img src="/Images/@Model.AnhBia" width="120"> (Ảnh hiện tại)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ngày cập nhật:</label>
            <div class="col-md-10">
                <input type="datetime" name="dNgayCapNhat" required value="@Convert.ToDateTime(Model.NgayCapNhat)" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Số lượng bán:</label>
            <div class="col-md-10">
                <input type="number" min="1" required name="iSoLuong" value="@Model.SoLuongBan" />
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Giá bán:</label>
            <div class="col-md-10">
                <input type="number" min="1" required name="mGiaBan" value="@Model.GiaBan" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Chủ đề:</label>
            <div class="col-md-10">
                @Html.DropDownList("MaCD")
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Nhà xuất bản:</label>
            <div class="col-md-10">
                @Html.DropDownList("MaNXB")
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="LUU THÔNG TIN" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("VỀ TRANG QUẢN LÝ SÁCH", "Index")
</div>

HoTuanPhuoc/Areas/admin/Views/Sach/Index.cshtml
@helper Truncate(string s, int length)
{
    if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)<text>...</text>
    }
}
@using HoTuanPhuoc.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 style="text-align: center"> Quản lý thông tin sách </h2>
<p>@Html.ActionLink("Thêm mới", "Create")</p>


@using (Html.BeginForm("Index", "Sach", FormMethod.Get, new { @class = "search-form" }))
{
    <p>
        <input type="text" name="strSearch"
               value="@ViewBag.Search" placeholder="Nhập sản phẩm cần tìm...." 
               class="form-control flex-1" />
        <input type="submit" value="Tìm kiếm" class="btn btn-primary" />
    </p>
}
<style>
    .flex-1 {
        flex: 1;
    }
</style>

@if (Model != null)
{
    if (Model.Count() > 0)
    {

        <table class="table">
            <tr>

                <th style="width:140px">
                    Tên sách
                </th>
                <th style="width:200px">
                    Mô tả
                </th>
                <th style="width:80px">
                    Ảnh bìa
                </th>
                <th style="width:100px">
                    Ngày cập nhật
                </th>
                <th style="width:80px">
                    Số lượng
                </th>
                <th style="width:80px">
                    Giá bán
                </th>
                <th style="width:100px">
                    Tên chủ đề
                </th>
                <th style="width:100px">
                    Tên nhà xuất bản
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {

                <tr>

                    <td>

                        @Truncate(item.TenSach, 50)
                    </td>
                    <td>
                        @Html.Raw(Html.Encode(Truncate(item.MoTa, 70)))

                    </td>
                    <td>
                        <img src="~/Images/@item.AnhBia" alt="Thumbnail Image" class="img-responsive img-rounded imgbook " style="width:50px" />
                    </td>
                    <td>
                        @Html.FormatValue(item.NgayCapNhat, "{0:dd/MM/yyyy}")
                    </td>
                    <td>
                        @item.SoLuongBan
                    </td>
                    <td>

                        @Html.FormatValue(item.GiaBan, "{0:#,##0}")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CHUDE.TenChuDe)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NHAXUATBAN.TenNXB)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Sach", new { id = item.MaSach })"
                           class="btn-warning btn">Sửa</a>
                        <a href="@Url.Action("Details", "Sach", new { id = item.MaSach })"
                           class="btn-primary btn">Chi tiết</a>
                        <a href="@Url.Action("Delete", "Sach", new { id = item.MaSach })"
                           class="btn btn-danger">Xóa</a>

                    </td>
                </tr>
            }

        </table>
        <div> Trang @(Model.PageNumber<=0 ? 0 : Model.PageNumber) / @Model.PageCount</div>
        <div class="Menutrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page, strSearch = ViewBag.Search }))
        </div>
    }
    else
    {


    }

}
<style>
    .Menutrang {
        display: inline;
        text-align: center;
    }
</style>